//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.reserva = new HashSet<reserva>();
        }
    
        public int id { get; set; }
        public string primeiro_nome { get; set; }
        public string ultimo_nome { get; set; }
        public string doc_rg { get; set; }
        public string doc_cpf { get; set; }
        public System.DateTime dt_nasc { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual ICollection<reserva> reserva { get; set; }
    }
}
