//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class comodidade
    {
        public comodidade()
        {
            this.quarto = new HashSet<quarto>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual ICollection<quarto> quarto { get; set; }
    }
}
