//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatura
    {
        public int id { get; set; }
        public int fk_reserva { get; set; }
        public decimal valor_reserva { get; set; }
        public System.DateTime dt_vencimento { get; set; }
        public Nullable<double> multa_diaria { get; set; }
        public System.DateTime dt_pagamento { get; set; }
    
        public virtual reserva reserva { get; set; }
    }
}
