//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_quartos
    {
        public int id { get; set; }
        public int andar { get; set; }
        public int numero { get; set; }
        public int tipo { get; set; }
        public int tamanho { get; set; }
        public int qtd_camas { get; set; }
        public decimal preco { get; set; }
        public Nullable<bool> ativo { get; set; }
        public int fk_quarto { get; set; }
    }
}
